name: Haskell CI - Stack based - test
# note: for the most part, shamelessly stolen from xmonad

on:
  push:
  pull_request:

jobs:
  build:
    name: Stack CI
    runs-on: macos-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v4

      - name: Get ghc version
        shell: bash
        run: |
          GHCVER=$(curl -L https://www.stackage.org/lts-22.34/ghc-major-version)
          echo "Got $GHCVER"
          echo "ghc=$GHCVER" >> $GITHUB_OUTPUT
        id: ghc-version

      - uses: haskell-actions/setup@v2
        name: Setup GHC ${{ steps.ghc-version.outputs.ghc }}
        id: hs-setup
        with:
          ghc-version: ${{ steps.ghc-version.outputs.ghc }}
          enable-stack: true

      - name: Update hackage index
        run: stack update

      - name: Pull in macOS dependencies
        if: runner.os == 'macOS'
        run: git submodule update --init

      - name: Build and test (macOS, dext)
        shell: bash
        if: runner.os == 'macOS'
        run: |
          stack install \
            --flag kmonad:dext \
            --extra-include-dirs=c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/include/pqrs/karabiner/driverkit:c_src/mac/Karabiner-DriverKit-VirtualHIDDevice/src/Client/vendor/include
      - name: upload files
        uses: actions/upload-artifact@v3
        with:
          name: kmonad
          path: /Users/runner/.local/bin/kmonad
